### ISSUE TITLE
App to review a star catalog FOT request

### ISSUE THREAD

**Issue by taldcroft** [sot/kadi-apps#13]
Independent ACA review of a star catalog used in anomaly recovery operations would be good.

The app could include:
- A text box to paste a FOT request
- Parse the input into the parameters necessary for `proseco.get_aca_catalog`
  - [parse_cm.csd](https://sot.github.io/parse_cm/#dot-fot-request-cmd-gen) to convert from the FOT request to an `AOSTRCAT` backstop command
  - [convert_aostrcat_to_acatable](https://cs.github.com/sot/kadi/blob/cd7acded08245af69290a85b9f5ebc602cddbfb4/kadi/commands/observations.py#L137) to convert from `AOSTRCAT` to an `ACATable`
-  From that `ACATable` and parameters stored in the comments, generate a new `ACATable` catalog corresponding exactly to the FOT request.
- Run sparkles on that catalog and return the corresponding HTML.
  - One issue is that sparkles wants to make files on a disk system including a PNG of the star catalog. Not sure how to handle that in this app. Some kind of tmp disk space writeable by the `kadi` user?

```
!$  Date: Thu 11-Aug-2022 19:27:00                                       $
!$  Generated by MATLAB StarViewer                                       $
!$  Generated for 2022:224:02:00:00.000                                  $
!$  MAN_ERR =  50.0,  DITHER =  8.0 (ARCSEC)                              $
!$  QUAT = -0.24849372, 0.40954561, -0.31440262, 0.81955735              $
!$  RA = 303.000000,  DEC = -31.000000,  ROLL = 309.138930               $
!$  SUN_PITCH = 156.791 (DEG),  OFF_NOM_ROLL =   0.104 (DEG)             $
!$  STARS/FIDUCIAL LIGHTS                       AC COORDINATES (ARCSEC)  $
!$  #  TYP          ID  RA(DEG)  DEC(DEG)    MAG MAXMAG Y-ANGLE Z-ANGLE  $
!$  *******************************************************************  $
!$  0  BOT   975307864 302.8990  -31.8494  8.220  6.720  2176.8 -2169.8  $
!$  1  BOT   975317760 303.2344  -31.4876  8.289  6.789  1816.4  -550.3  $
!$  2  BOT   975318288 303.1135  -31.0031  8.441  6.941   230.0   264.6  $
!$  3  BOT   975308432 302.5790  -31.5214  8.497  6.997   642.2 -2188.3  $
!$  4  BOT   975319664 303.4827  -30.9031  8.859  7.359   673.2  1374.7  $
!$  5  BOT   975311216 302.8537  -30.7986  8.862  7.362  -847.6   106.4  $
!$  6  BOT   975317376 303.5646  -31.4803  9.347  7.847  2438.7   250.2  $
!$  7  GUI   975307608 302.8302  -31.3983  9.312  7.812   783.2 -1310.1  $
!$  7  ACQ   975313552 302.7063  -30.6623  9.254  7.754 -1516.0    61.1  $
!$                                                                       $
SCS_CATEGORY, VEHICLE
RTSLOAD,A_CATUP,SCS_NUM=171,
NUMENT=9,
AQIM1=0,
AQY1=0.01055343,
AQZ1=-0.01051968,
AQMBRT1=6.72046185,
AQMFNT1=9.72046185,
AQRES1='H',
AQBOX1=28,
AQSIZE1=2,
AQFLG1=2,
...
AQIM9=7,
AQY9=-0.00734975,
AQZ9=0.00029616,
AQMBRT9=7.75386715,
AQMFNT9=10.75386715,
AQRES9='H',
AQBOX9=8,
AQSIZE9=2,
AQFLG9=0
```

**Comment by jeanconn** [comment]
Per conversation, let's just make an updated version of the FOT request review notebook and put it in skanb and link from the ACA response google docs page.

**Comment by jeanconn** [comment]
I think this is done for now with the review notebooks.
